[colors.primary]
background = '#1e2030'
foreground = '#7f85a3'

[colors.cursor]
text   = '#7f85a3'
cursor = '#808080'

[colors.normal]
black   = '#2e324d'
red     = '#ff5370'
green   = '#4fd6be'
yellow  = '#ffc777'
blue    = '#3e68d7'
magenta = '#bc7bfc'
cyan    = '#86e1fc'
white   = '#d0d0d0'

[colors.bright]
black   = '#828bb8'
red     = '#ff98a4'
green   = '#c3e88d'
yellow  = '#ffc777'
blue    = '#82aaff'
magenta = '#cb6afc'
cyan    = '#b4f9f8'
white   = '#5f8787'
